Name:           ros-lunar-costmap-converter
Version:        0.0.9
Release:        0%{?dist}
Summary:        ROS costmap_converter package

Group:          Development/Libraries
License:        BSD
URL:            http://wiki.ros.org/costmap_converter
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-lunar-costmap-2d
Requires:       ros-lunar-cv-bridge
Requires:       ros-lunar-dynamic-reconfigure
Requires:       ros-lunar-geometry-msgs
Requires:       ros-lunar-message-runtime
Requires:       ros-lunar-pluginlib
Requires:       ros-lunar-roscpp
Requires:       ros-lunar-std-msgs
BuildRequires:  ros-lunar-catkin
BuildRequires:  ros-lunar-costmap-2d
BuildRequires:  ros-lunar-cv-bridge
BuildRequires:  ros-lunar-dynamic-reconfigure
BuildRequires:  ros-lunar-geometry-msgs
BuildRequires:  ros-lunar-message-generation
BuildRequires:  ros-lunar-pluginlib
BuildRequires:  ros-lunar-roscpp
BuildRequires:  ros-lunar-std-msgs

%description
A ros package that includes plugins and nodes to convert occupied costmap2d
cells to primitive types.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/lunar/setup.sh" ]; then . "/opt/ros/lunar/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/lunar" \
        -DCMAKE_PREFIX_PATH="/opt/ros/lunar" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/lunar/setup.sh" ]; then . "/opt/ros/lunar/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/lunar

%changelog
* Mon May 28 2018 Christoph Rösmann <christoph.roesmann@tu-dortmund.de> - 0.0.9-0
- Autogenerated by Bloom

* Thu May 17 2018 Christoph Rösmann <christoph.roesmann@tu-dortmund.de> - 0.0.8-0
- Autogenerated by Bloom

* Wed Sep 20 2017 Christoph Rösmann <christoph.roesmann@tu-dortmund.de> - 0.0.7-0
- Autogenerated by Bloom

* Mon Sep 18 2017 Christoph Rösmann <christoph.roesmann@tu-dortmund.de> - 0.0.6-0
- Autogenerated by Bloom

